version: '3.7'

services:
  db:
    build:
      context: .
      dockerfile: mySql.Dockerfile
    image: memories-db-mysql
    container_name: memories-db
    ports:
      - '3303:3306'
    environment:
      MYSQL_ROOT_PASSWORD: Password1

    restart: always
  graphql:
    image: memories-server-graphql:latest
    container_name: memories-server
    build: .
    depends_on:
      - db
    environment:
      NODE_ENV: local
      JWT_SECRET: qowiueojwojfalksdjoqiwueo
      DB_HOST: db
    ports:
      - 4003:4000