version: '3.7'

services:
  db:
    build:
      context: .
      dockerfile: mySql.Dockerfile
    image: mysql-memories
    container_name: mysql-memories
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: Password1

    restart: always
  # api:
  #   container_name: parnteruser-api
  #   build: .
  #   depends_on:
  #     - db
  #   ports:
  #     - "8380:80"
