version: '3.7'

services:
  db:
    build:
      context: .
      dockerfile: mySql.Dockerfile
    image: mysql-memories
    container_name: mysql-memories
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: Password1

    restart: always
  graphql:
    image: graphql-gateway:latest
    build: .
    depends_on:
      - db
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
  # api:
  #   container_name: parnteruser-api
  #   build: .
  #   depends_on:
  #     - db
  #   ports:
  #     - "8380:80"
