name: Deploy Graphql Server

on: deployment

env:
  PROJECT: a4bird-memories
  AWS_ACCOUNT_NUMBER: ${{secrets.AWS_ACCOUNT_NUMBER}}
  AWS_PRIMARY_REGION: ap-southeast-2
  AWS_ROLE_TO_ASSUME: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/admin
  AWS_ECR_REPO_NAME: memories-server
  PREV_ENV: ""

jobs:
  setup:
    name: Setup Variables
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.branch-slug.outputs.branch }}
      slug: ${{ steps.branch-slug.outputs.slug }}
    steps:
      - name: Create Slug
        id: branch-slug
        run: |
          branch_ref=${GITHUB_REF#refs/heads/}
          branch="${GITHUB_HEAD_REF:-$branch_ref}"
          slug="${branch//\//-}"
          echo ::set-output name=branch::${branch}
          echo ::set-output name=slug::${slug,,}
      - name: Display branch slug output
        id: branch-slug-output
        run: |
          echo "branch is ${branch}"
          echo "slug is ${slug}"
        env:
          branch: ${{steps.branch-slug.outputs.branch}}
          slug: ${{steps.branch-slug.outputs.slug}}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Set environment variables for Staging
        if: github.event.deployment.environment == 'Staging'
        run: |
          echo "::set-env name=PREV_ENV::Development"

      - name: Set environment variables for Sandbox
        if: github.event.deployment.environment == 'Sandbox'
        run: |
          echo "::set-env name=PREV_ENV::Staging"

      - name: Set environment variables for Production
        if: github.event.deployment.environment == 'Production'
        run: |
          echo "::set-env name=PREV_ENV::Sandbox"

      - name: Get deployments from the preceding environment
        if: env.PREV_ENV != ''
        id: check_previous_stage
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/deployments?sha=:sha&environment=:environment
          repository: ${{ github.repository }}
          sha: ${{ github.sha }}
          environment: ${{ env.PREV_ENV }}
          mediaType: |
            previews:
              - ant-man
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check previous deployments
        if: env.PREV_ENV != '' && steps.check_previous_stage.outputs.data == '[]'
        run: |
          echo "::error ::Must deploy to ${{ env.PREV_ENV }} environment before ${{ github.event.deployment.environment}}"
          exit 1

      - name: Fetch docker build tag
        run: |
          echo "::info ::Deployment payload: ${{ toJSON(github.event.deployment) }}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "${{ env.NODE_VERSION }}"

      - name: Install Dependencies
        run: npm run cdk-install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        id: login-aws
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_PRIMARY_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200

      - name: Deploy to ap-southeast-2
        id: cdk-deploy
        env:
          AWS_TAG_REPOSITORY: ${{ github.repository }}
          AWS_CDK_DEPLOY_ACCOUNT: ${{ steps.login-aws.outputs.aws-account-id }}
          AWS_CDK_DEPLOY_REGION: ap-southeast-2
          AWS_CDK_STACK_ID: memory-server-${{ needs.setup.outputs.slug }}
          AWS_CERTIFICATE_ARN: arn:aws:acm:${{ env.AWS_PRIMARY_REGION }}:${{ steps.login-aws.outputs.aws-account-id }}:certificate/${{ secrets.AWS_CERTIFICATE_ID }}
          AWS_ECR_REPO_ARN: arn:aws:ecr:${{ env.AWS_PRIMARY_REGION }}:${{ secrets.AWS_ACCOUNT_NUMBER }}:repository/${{ env.AWS_ECR_REPO_NAME }}
          AWS_FARGATE_CLUSTER_NAME: ${{ env.PROJECT }}
          AWS_FARGATE_SERVICE_NAME: ${{ needs.setup.outputs.slug }}
          AWS_FARGATE_DESIRED_COUNT: 2
          AWS_FARGATE_MIN_CAPACITY: 2
          AWS_FARGATE_MAX_CAPACITY: 4
          AWS_ROUTE53_DOMAIN: a4brd.tk
          AWS_ROUTE53_SUBDOMAIN: memories-server-${{ needs.setup.outputs.slug }}
          DOCKER_IMAGE_TAG: ${{ github.event.deployment.payload.docker_tag }}
          CONTAINER_APOLLO_INTROSPECTION_ENABLED: false
          CONTAINER_APOLLO_PLAYGROUND_ENABLED: false
          CONTAINER_APOLLO_REPORT_SCHEMA: true
          CONTAINER_APOLLO_GRAPH_VARIANT: dev-${{ needs.setup.outputs.slug }}
          CONTAINER_APOLLO_SERVER_USER_VERSION: ${{ github.event.deployment.payload.docker_tag }}
        run: |
          npm run cdk-deploy
          echo ::set-output name=url::https://${AWS_ROUTE53_SUBDOMAIN}.${AWS_ROUTE53_DOMAIN}
          
